const projects = [
  {
    id: 1,
    title: "Birthday Reminder",
    img: "./images/birthday.png",
    createdAt: "1 February 2023",
    description: "useState and event handler usage",
    link: "/birthday",
    source: "https://github.com/prasetyoow/react-projects",
  },
  {
    id: 2,
    title: "Tours",
    img: "./images/tours.png",
    createdAt: "2 February 2023",
    description: "useState, event handler, components and Props usage",
    link: "/tours",
    source: "https://github.com/prasetyoow/react-projects",
  },
  {
    id: 3,
    title: "Reviews",
    img: "./images/reviews.png",
    createdAt: "3 February 2023",
    description: "useState and event handler usage",
    link: "/reviews",
    source: "https://github.com/prasetyoow/react-projects",
  },
  {
    id: 4,
    title: "Accordion",
    img: "./images/accordion.png",
    createdAt: "4 February 2023",
    description: "useState, event handler, components and Props usage",
    link: "/accordion",
    source: "https://github.com/prasetyoow/react-projects",
  },
  {
    id: 5,
    title: "Menu",
    img: "./images/menu.png",
    createdAt: "5 February 2023",
    description: "useState, event handler, components and Props usage",
    link: "/menu",
    source: "https://github.com/prasetyoow/react-projects",
  },
  {
    id: 6,
    title: "Tabs",
    img: "./images/tabs.png",
    createdAt: "6 February 2023",
    description: "useState and event handler usage",
    link: "/tabs",
    source: "https://github.com/prasetyoow/react-projects",
  },
  {
    id: 7,
    title: "Slider",
    img: "./images/slider.png",
    createdAt: "7 February 2023",
    description: "useState and event handler usage",
    link: "/slider",
    source: "https://github.com/prasetyoow/react-projects",
  },
  {
    id: 8,
    title: "Lorem Ipsum Generator",
    img: "./images/lorem.png",
    createdAt: "8 February 2023",
    description: "useState and event handler usage",
    link: "/loremipsum",
    source: "https://github.com/prasetyoow/react-projects",
  },
  {
    id: 9,
    title: "Color Generator",
    img: "./images/color.png",
    createdAt: "9 February 2023",
    description: "useState, event handler, components and Props usage",
    link: "/colorgenerator",
    source: "https://github.com/prasetyoow/react-projects",
  },
];

export default projects;
